module.exports = {
    saveSuccess: 201,
    createdMessage: 'Record Created',
    updatedMessage: 'Record Updated',
    deletedMessage: 'Record Deleted',
    getMessage: 'Records Found',
    ok: 200,
    badRequest: 400,
    internalServerError: 500,
    notFound: 404,
    unauthorized: 401,
    forbidden: 403,
    tokenError: 'No token provided!',
    unauthorizedMessage: 'Unauthorized!',
    errorNotFound: 'No Record Found',
    internalServerErrorMessage: 'Internal Server Error',
    fieldNotExistMessage: 'This Field Does not Exist On The Model',
    registrationNotFound: 'No Registration Record With This Id',
    errorCreatingRecord: 'Error in Creating Record',
    noCategoryParentMessage: 'No Category found exist with this parent_id',
};
